version: 0.0
Resources:
- TargetService:
Type: AWS::ECS::Service
Properties:
TaskDefinition: "arn:aws:ecs:us-east-1:156962844638:task-definition/fse-pms-xxxx-auth-TD:1"
LoadBalancerInfo:
ContainerName: "pms-xxxx-auth-Container"
ContainerPort: 8000
PlatformVersion: "LATEST"